### ISSUE TITLE
"global level of red" different in resized image 

### ISSUE THREAD

**Issue by berger-n** [buda-base/buda-iiif-server#46]
in some of the first volumes of [bdr:W4CZ5369](http://library-dev.bdrc.io/scripts/embed-iframe.html?work=bdr:W4CZ5369&origin=localhost&lang=bo-x-ewts),
[full size](https://iiif.bdrc.io/bdr:V4CZ5369_I1KG9127::I1KG91270004.jpg/full/max/0/default.jpg) image and [resized](https://iiif.bdrc.io/bdr:V4CZ5369_I1KG9127::I1KG91270004.jpg/full/1250,/0/default.jpg) image seem to have differents "red level" of something
resulting in unsatisfying [OpenSeaDragon viewer](http://library-dev.bdrc.io/scripts/OSD-test.html) behavior when zooming in/out due to this "red level" changing
below is a mix between both images, left is fullsize and right 1250px width:
![image](https://user-images.githubusercontent.com/33383857/74863857-e1daf880-534e-11ea-9cc4-5e91de3068e5.png)

**Comment by eroux** [comment]
The problems i that the full version (that is not processed by hymir) has a [color profile](https://en.wikipedia.org/wiki/ICC_profile) (AdobeRGB) that is not kept in the processed (resized) image. It really should be retained, it's very important. It's just something in the metadata, it should necessitate special development... @MarcAgate can you take a look?

**Comment by MarcAgate** [comment]
Do we have an exhaustive list of the format being stored on S3 and served by iiifserver (Tiff, Jpeg, anything else ?) Looks like not all formats are supported when it comes to read ICC profile from image metadata using java. Also, it looks like hymir is not handling IIOMetadata when reading images.

**Comment by eroux** [comment]
Tif, jpeg and png are the most important. It's really a necessary feature so if there's a limitation from hymir we need to report the issue and fix it

**Comment by MarcAgate** [comment]
As far as I can tell, there's nothing in hymir that reads IIC profile from readers in order to parameterize writers... Also (for instance) , twelvemonkeys seems to handle TIFF and JPEG very differently regarding metadata and ICC_PROFILE. I need to investigate this and to reports the issue to hymir anyway.

**Comment by eroux** [comment]
Ok, let's talk tomorrow, if you have a demo code in a java test file of something that we can do with the twelvemonkeys codecs that we can't with imageio-jnr that will be perfect

**Comment by MarcAgate** [comment]
Some issue status here:

1) We discovered that when running iiifserv on my machine (mac), the issue disappeared.
2) We then realized that we were using java Hot spot 8 on my mac and OpenJdk 8 on ec2 and that java version could matter
3) We then observed that the IIC profile of the original image wasn't the same as the read image
for instance:
**Original ICC**: 
```
icc:copyright: Copyright 2000 Adobe Systems Incorporated
icc:description: Adobe RGB (1998)
Profile-icc: 560 bytes
```
**ICC of the read image:**
```
icc:copyright: Copyright (c) 1998 Hewlett-Packard Company
icc:description: sRGB IEC61966-2.1
icc:manufacturer: IEC http://www.iec.ch
icc:model: IEC 61966-2.1 Default RGB colour space - sRGB
Profile-icc: 3144 bytes
```
4) We tried the following workaround in order to preserve the original ICC profile: [here](https://github.com/haraldk/TwelveMonkeys/issues/482)

However, in the jpeg case:
Hymir is using `com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader`

This reader exposes 2 ImageTypeSpecifier:

```
javax.imageio.ImageTypeSpecifier$Interleaved
javax.imageio.ImageTypeSpecifier$Grayscale
```
The tests show that only the Interleaved ImageType is supported

**On the other end, the twelvemonkeys JPEGImageReader getRawImageType(imageIndex) method returns null for the computed imageIndex and therefore the workaround doesn't work**

At this point, assuming the issue is really coming from java versions and that the provided workaround is valid, we might try other readers with that workaround.

**Comment by eroux** [comment]
thanks! please make a small demo `.java` file that we can elaboate on to find some solutions to this issue

**Comment by MarcAgate** [comment]
Some additional info from my investigations/tests:

if I save http://iiif.bdrc.io/bdr:V4CZ5369_I1KG9127::I1KG91270004.jpg/full/2000,/0/default.jpg as default.jpg
and I do: `identify -verbose default.jpg |grep icc`, nothing is returned

If I save http://localhost:8080/bdr:V4CZ5369_I1KG9127::I1KG91270004.jpg/full/2000,/0/default.jpg as defaultMAC.jpg and I do `identify -verbose defaultMAC.jpg |grep icc`, I get:

```
icc:copyright: Copyright (c) 1998 Hewlett-Packard Company
icc:description: sRGB IEC61966-2.1
icc:manufacturer: IEC http://www.iec.ch
icc:model: IEC 61966-2.1 Default RGB colour space - sRGB
Profile-icc: 3144 bytes
```

However, while there is no icc profile in the first case (default.jpeg) there is ICC color profile equivalent Info:

```
Colorspace: sRGB
  Type: TrueColor
  Base type: Undefined
  Endianess: Undefined
  Depth: 8-bit
  Channel depth:
    Red: 8-bit
    Green: 8-bit
    Blue: 8-bit
etc...
```

**Comment by eroux** [comment]
Yes, no color profile is roughly equivalent to `sRGB` (although embedding the `sRGB` profile is better). Neither of these are the correct one (`Adobe RGB (1998)`)

**Comment by eroux** [comment]
so, after a full day of debugging, I have a solution that is not really satisfactory but allows the output images to have at least the correct colors. The changes that need to be made are:
- not using the TurboJpeg library for reading, because it can't read the icc profile and completely loses it (that's what's currently happening, Marc I think it doesn't happen on your machine because you're not using the TurboJpeg reader)
- using the TwelveMonkeys reader converts the image pixel values to sRGB which is not what we want and slows things down, but at least we have the colors right
- we could continue to use the TurboJpeg writer as the output image doesn't need a special icc profile (because it's alraedy converted to sRGB)
- OTOH, it also doesn't write any metadata, which is not very good and I think we should measure the performance impact of using the TwelveMonkeys writer so that we can write metadata

We should continue to push things in the direction of embedding the icc profile instead of converting to sRGB, but the behavior seems to be deeply rooted in Java so that will make things hard... more on https://github.com/haraldk/TwelveMonkeys/issues/528

**Comment by MarcAgate** [comment]
Well, I finally found a way to get what we wanted from the apache commons-imaging API.
This is now implemented in the iiif processing flow, and the first tests show it is working properly.
The ICC profile is read from the bytes coming from S3 or those cached in JCS, then forwarded to the processImage method where the raw Buffered image is associated with it.

I haven't pushed that to ec2 as it requires some cleanup and more testing. As far as I can tell, this forwarding is logically writer independent.

**Comment by eroux** [comment]
Ok! Can you also add it to the test file please?

**Comment by eroux** [comment]
sorry, I just saw you did

**Comment by MarcAgate** [comment]
Ok, I believe this is issue is now fixed. @berger-n Can we close it ?

**Comment by berger-n** [comment]
@MarcAgate I have just noticed that the issue still occurs in `iiif-dev`
compare zooming in http://library-dev.bdrc.io/scripts/OSD-test-iiif.html (ok)
and in http://library-dev.bdrc.io/scripts/OSD-test-iiif-dev.html (not ok)
